name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add wasm32-unknown-unknown
      id: add_wasm32
      run: rustup target add wasm32-unknown-unknown

    - name: Build Release
      run: make

    - name: Get short SHA
      id: short_sha
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.short_sha.outputs.sha8 }}
        release_name: Release from ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Log Release Asset
      id: upload-log
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./log/target/wasm32-unknown-unknown/release/log.wasm
        asset_name: log.wasm
        asset_content_type: application/wasm

    - name: Upload Numeric Release Asset
      id: upload-numeric
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./numeric/target/wasm32-unknown-unknown/release/numeric.wasm
        asset_name: numeric.wasm
        asset_content_type: application/wasm

    - name: Upload HostString Release Asset
      id: upload-hoststring
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./hoststring/target/wasm32-unknown-unknown/release/hoststring.wasm
        asset_name: hoststring.wasm
        asset_content_type: application/wasm
